# Generated by Django 3.1.3 on 2021-01-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_donetodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoneTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=254)),
                ('start_date', models.DateTimeField()),
                ('finished_date', models.DateTimeField()),
                ('difference', models.DateTimeField()),
            ],
        ),
    ]
