# Generated by Django 3.1.3 on 2021-01-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_donetodo_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_inserted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
