# Generated by Django 3.1.3 on 2021-01-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_donetodo_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='donetodo',
            name='difference',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
